[package]
name = "atcoder-upcoming-contests"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
chrono = "0.4.40"
reqwest = "0.12.15"
scraper = "0.23.1"
serde = "1.0.219"
shuttle-axum = "0.53.0"
shuttle-runtime = "0.53.0"
tokio = "1.28.2"
